name: Proyecto HT.BUSCADOR
run-name: ${{ github.actor }} est치 ejecutando Snakemake 游냀
on: [push]
  #schedule:
  #- cron: '0 10 * * *'
jobs:
  Ejecuto-Proyecto-HT-BUSCADOR:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        SPOTIPY_REFRESH_TOKEN: ${{ secrets.SPOTIPY_REFRESH_TOKEN }}
    steps:
      - run: echo "游꿀 Tareas activadas autom치ticamente debido a un evento ${{ github.event_name }}"
      - run: echo "游냖 Las tareas est치n corriendo en un servidor ${{ runner.os }} alojado en GitHub"
      - run: echo "游댍 El nombre del branch es ${{ github.ref }} y su repositorio es ${{ github.repository }}"
      - name: Verificar el c칩digo del repositorio
        uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: ht.buscador
          environment-file: environment.yml
          auto-activate-base: false
      #- name: Set up Quarto
      #  uses: quarto-dev/quarto-actions/setup@v2
      - name: Render Quarto
        run: scripts/principal.bash
      - name: Configuro git en el runner
        run: |
          git config --local user.email "noreply@github.com"
          git config --local user.name "GitHub"
      - name: Commit de los cambios en el repositorio
        run: |
          git add .
          git commit -m "sitio web generado con 칰ltimo valor estimado de turbidez"
          git push origin main
      - run: echo "游꼞 El estado final es = ${{ job.status }}."
